### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by creacionesintegrales** [VFPX/AATest#1]
Doug,
Existe algún tutorial que pueda seguir para aprender cómo se utiliza el AATest?

Saludos,
Francisco Prieto

**Comment by DougHennig** [comment]
I do not think so.

**Comment by eselje** [comment]
What is an AATest?

**Comment by creacionesintegrales** [comment]
El AATest es una herramienta que viene distribuida con VFP en la carpeta \Tools\Test y que sirve básicamente para realizar test del código que programes.
